Feature/music album
andym80/ruby-capstone pull request #67
Opened 2022-11-15 20:13 UTC by AmaliaGM

- Create MusicAlbum class in a separate .rb file.
- Create Genre class with an association to the Item class (in a separate .rb file).
- All MusicAlbum class properties visible in the diagram should be defined and set up in the constructor method.
- All Genre class properties visible in the diagram should be defined and set up in the constructor method.
- Implement methods:
add_item method in the Genre class
should take an instance of the Item class as an input
should add the input item to the collection of items
should add self as a property of the item object (by using the correct setter from the item object)
can_be_archived?() in the MusicAlbum class
should override the method from the parent class
should return true if parent's method returns true AND if on_spotify equals true
otherwise, it should return false

2022-11-15 20:35 UTC, carlosmuerto requested changes
There is some change, please read the comments:
- please add the issues you are closing in the PR description like this` - close #<number of the issue>`

2022-11-15 20:35 UTC, carlosmuerto commented on src/genre.rb
> +class Genre < Item
Genre does not inherit from Item, Genre is a component of Item

2022-11-15 20:35 UTC, carlosmuerto commented on src/genre.rb
> +  @items.push(item)
did you are adding twice to the items list?

2022-11-15 20:35 UTC, carlosmuerto commented on src/music-album.rb
> +    super(*args)
the arguments of the Item are not optional add all to the constructor 

```ruby
def initialize(  # rubocop:disable Metrics/ParameterLists
  genre, 
  author, 
  source, 
  label, 
  publish_date, 
  on_spotify
) 
  super(genre, author, source, label, publish_date)
  @on_spotify = on_spotify
end
```

2022-11-15 20:35 UTC, carlosmuerto commented on src/genre.rb
> +def add_item(_items)
Add_item(item) method need to be called when a item is constructed

2022-11-15 20:51 UTC, carlosmuerto requested changes
please use the ` - close #<number of the issue>` format to identify what issue are your addressing
it will show like this

- close #30

2022-11-15 21:03 UTC, andym80 requested changes
- [ ] Check

2022-11-15 21:25 UTC, AmaliaGM commented
> * [ ]  Check

No se ven tus comentarios

2022-11-16 23:35 UTC, carlosmuerto approved these changes

2022-11-17 13:05 UTC, andym80 approved these changes

2022-11-17 14:37 UTC, merged